### ISSUE TITLE
Why I processed the PCM Audio Data with no effect?

### ISSUE THREAD

**Issue by LeventureQys** [jurihock/RealTimeDeepFilterNet#2]
I See In the code that it can process float data,And I transfer my wav audio into pcm audio data with ffmpeg.

However,the keyboard background sound not filted,And I can't process your example audio x.wav after transfer to PCM data

#include <iostream>
#include <fstream>
#include <vector>
#include <DeepFilter.h>
#include <FFT.h>
#include <STFT.h>

int main()
{
  DeepFilter filter;

  //Try Read File
  // std::cout << filter.probe() << std::endl;
  std::ifstream pcmFile("D:/temp/output.pcm", std::ios::binary);
  if (!pcmFile.is_open()) {
    std::cerr << "Failed to open PCM file." << std::endl;
    return -1;
  }
  auto samplerate = filter.samplerate();
  auto framesize = filter.framesize();
  auto hopsize = filter.hopsize();
  auto chronometry = true;
  auto samples = static_cast<size_t>(10 * samplerate);

  auto fft = std::make_shared<FFT>();
  auto stft = std::make_shared<STFT>(fft, framesize, hopsize, chronometry);

  std::vector<float> x;
  // Read PCM File
  int16_t sample;
  while (pcmFile.read(reinterpret_cast<char*>(&sample), sizeof(sample))) {
    // 将int16_t的样本转换为float
    x.push_back(static_cast<float>(sample) / 32768.0f); // 32768.0f normalize to [-1, 1]
  }
  pcmFile.close();

  // output vector should have same size with x
  std::vector<float> y(x.size());
  (*stft)(x, y, [&](std::span<std::complex<float>> dft)
  {
      filter(dft, dft);
  });
  
  // get processed data
    // save processed pcm data
  std::ofstream outFile("D:/temp/DeepFilter.pcm", std::ios::binary);

  if (!outFile.is_open()) {
    std::cerr << "Failed to open output PCM file." << std::endl;
    return -1;
  }

  for (const auto& sample : y) {
    int16_t outSample = static_cast<int16_t>(sample * 32768.0f); // get int data
    outFile.write(reinterpret_cast<const char*>(&outSample), sizeof(outSample));
  }

  outFile.close();
}

**Comment by LeventureQys** [comment]
oh,just find out it's not done yet

**Comment by jurihock** [comment]
Yes, it is not complete right now.
