### ISSUE TITLE
about realtime stream mode question

### ISSUE THREAD

**Issue by DonkeyHang** [jurihock/RealTimeDeepFilterNet#4]
Hi,

Thank you for your Repo. I don't understand Rust, so learning about the calculation of ERB from your work has been very useful.

Recently, I modified the DeepFilterNet project to operate in a streaming mode (processing every 10ms/20ms). I have some questions that I would like to discuss with you.

In your repository, it mentions "realtime," but in practice, during calculations, it still loads the entire audio file, splits it, and processes it in chunks (at least needing 4*480 samples). For example, if my signal has a sampling rate of 48kHz and a total of 480,000 samples, I would split it into 1,000 frames for processing (with a hop size of 480, which is the frame length). However, in actual processing, I cannot obtain more than 20ms of data, which results in significant latency, So I revamped the entire project. I aim for each input to be only 2480 samples, and simultaneously output 2480 samples. This is because I found that the model requires at least 3*480 points for processing, as it needs to perform two 960-point FFT transformations, with 480 points being in an overlapping state.

but here get some question:
1: in deepfilternet3.py file, when we start processing in DfNet.forward()
`e0, e1, e2, e3, emb, c0, lsnr = self.enc(feat_erb, feat_spec)`
the feat_erb.shape : torch.Size[1, 1, 1000, 32] and feat_spec.shape:torch.Size[1, 2, 1000, 96] got the e0.shape:torch.Size[1, 64, 1000, 32], 
when i only use feat_erb.shape : torch.Size[1, 1, 2, 32] and eat_spec.shape:torch.Size[1, 2, 2, 96], got the e0.shape:torch.Size[1, 64, 2, 32] is not equal than origin e0.shape:torch.Size[1, 64, 0:1 32],

So is processing two frames at a time not feasible? How many frames are needed at a minimum to meet the requirements?

**Comment by jurihock** [comment]
1. This repo is not finished yet.
2. I'm not the inventor of the DeepFilterNet. Please ask the inventor of DeepFilterNet for DeepFilterNet related details.

**Comment by DonkeyHang** [comment]
> 1. This repo is not finished yet.
> 2. I'm not the inventor of the DeepFilterNet. Please ask the inventor of DeepFilterNet for DeepFilterNet related details.

ok, thank you,
